// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a simplified version for the MVP

package grpc

import (
	"google.golang.org/protobuf/types/known/timestamppb"
)

type Job struct {
	Id         string                 `json:"id"`
	Type       string                 `json:"type"`
	Payload    []byte                 `json:"payload"`
	Priority   int32                  `json:"priority"`
	Attempts   int32                  `json:"attempts"`
	MaxRetries int32                  `json:"max_retries"`
	RunAt      *timestamppb.Timestamp `json:"run_at"`
	LeasedAt   *timestamppb.Timestamp `json:"leased_at"`
	CreatedAt  *timestamppb.Timestamp `json:"created_at"`
	Queue      string                 `json:"queue"`
	LeaseId    string                 `json:"lease_id"`
}

type LeaseRequest struct {
	WorkerId        string `json:"worker_id"`
	Queue           string `json:"queue"`
	MaxJobs         int32  `json:"max_jobs"`
	LeaseTtlSeconds int32  `json:"lease_ttl_seconds"`
}

type JobAck struct {
	JobId        string `json:"job_id"`
	WorkerId     string `json:"worker_id"`
	LeaseId      string `json:"lease_id"`
	Success      bool   `json:"success"`
	ErrorMessage string `json:"error_message"`
}

type JobAckResponse struct {
	Acknowledged bool   `json:"acknowledged"`
	Message      string `json:"message"`
}
