package quorrapb_test

import (
	"testing"
	"time"

	"github.com/Stiven-Gjekaj/GoQuorra/internal/quorrapb"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// The generated types must really be protobuf messages.
//
// This is the test the rebuild owes the reader. The version before it carried
// two files headed "Code generated by protoc-gen-go. DO NOT EDIT." that were
// written by hand, and whose messages were plain Go structs. They compiled,
// they looked right in a review, and the gRPC codec refused every one of them
// at run time, because it asks a message to marshal itself and a plain struct
// cannot. Nothing short of running a call could see it.
//
// A compile time assignment to proto.Message would have caught that file. The
// round trip is here as well, because a message can satisfy the interface and
// still carry a field the wire format drops.
func TestTheGeneratedTypesAreProtobufMessages(t *testing.T) {
	messages := []proto.Message{
		&quorrapb.Job{},
		&quorrapb.LeaseRequest{},
		&quorrapb.LeaseResponse{},
		&quorrapb.ReportRequest{},
		&quorrapb.ReportResponse{},
	}

	for _, message := range messages {
		if message.ProtoReflect().Descriptor() == nil {
			t.Errorf("%T carries no descriptor", message)
		}
	}
}

func TestAJobSurvivesTheWire(t *testing.T) {
	expires := time.Date(2026, 1, 1, 12, 0, 30, 0, time.UTC)
	sent := &quorrapb.Job{
		Id:             "6f1c0c64-1111-2222-3333-444455556666",
		Type:           "email",
		Payload:        []byte(`{"to":"a@b.c"}`),
		Queue:          "mail",
		Priority:       7,
		Attempts:       2,
		MaxRetries:     5,
		LeaseId:        "8de1a3d0-1111-2222-3333-444455556666",
		LeaseExpiresAt: timestamppb.New(expires),
	}

	raw, err := proto.Marshal(sent)
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}
	if len(raw) == 0 {
		t.Fatal("a job with every field set marshalled to nothing")
	}

	got := &quorrapb.Job{}
	if err := proto.Unmarshal(raw, got); err != nil {
		t.Fatalf("Unmarshal: %v", err)
	}

	if !proto.Equal(sent, got) {
		t.Errorf("the job changed on the wire:\nsent %v\ngot  %v", sent, got)
	}
	if !got.GetLeaseExpiresAt().AsTime().Equal(expires) {
		t.Errorf("lease expiry = %s, want %s", got.GetLeaseExpiresAt().AsTime(), expires)
	}
}

func TestALeaseRequestCarriesItsDuration(t *testing.T) {
	sent := &quorrapb.LeaseRequest{
		WorkerId: "worker-1",
		Queue:    "default",
		MaxJobs:  5,
		LeaseTtl: durationpb.New(45 * time.Second),
	}

	raw, err := proto.Marshal(sent)
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}

	got := &quorrapb.LeaseRequest{}
	if err := proto.Unmarshal(raw, got); err != nil {
		t.Fatalf("Unmarshal: %v", err)
	}
	if d := got.GetLeaseTtl().AsDuration(); d != 45*time.Second {
		t.Errorf("lease ttl = %s, want 45s", d)
	}
}

// An unset outcome must not mean success.
//
// Zero is what an older client sends, and what a new field left unwritten
// sends. Naming that value UNSPECIFIED rather than SUCCEEDED is what lets the
// server refuse it instead of retiring a job nobody finished.
func TestAnUnsetOutcomeIsUnspecified(t *testing.T) {
	if quorrapb.Outcome(0) != quorrapb.Outcome_OUTCOME_UNSPECIFIED {
		t.Fatal("the zero outcome is not UNSPECIFIED, so an unset field carries a meaning")
	}

	empty := &quorrapb.ReportRequest{}
	if empty.GetOutcome() != quorrapb.Outcome_OUTCOME_UNSPECIFIED {
		t.Errorf("an empty report reads as %v", empty.GetOutcome())
	}
}

// A refusal keeps its own number on the wire.
//
// The four outcomes travel as numbers, and a refusal that arrived as a
// success would retire a job nobody finished, while one that arrived as a
// plain failure would be retried until the attempts ran out. Both are silent.
// This pins the number and the round trip together, because the number is the
// part a later edit can move.
func TestARefusalSurvivesTheWire(t *testing.T) {
	if quorrapb.Outcome_OUTCOME_REFUSED != 3 {
		t.Errorf("a refusal travels as %d, want 3", quorrapb.Outcome_OUTCOME_REFUSED)
	}

	sent := &quorrapb.ReportRequest{
		JobId:   "6f1c0c64-0000-0000-0000-000000000000",
		LeaseId: "0d3a9d8e-0000-0000-0000-000000000000",
		Outcome: quorrapb.Outcome_OUTCOME_REFUSED,
		Error:   "the payload names no account",
	}

	raw, err := proto.Marshal(sent)
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}

	got := &quorrapb.ReportRequest{}
	if err := proto.Unmarshal(raw, got); err != nil {
		t.Fatalf("Unmarshal: %v", err)
	}
	if got.GetOutcome() != quorrapb.Outcome_OUTCOME_REFUSED {
		t.Errorf("outcome = %v, want a refusal", got.GetOutcome())
	}
	if got.GetError() != sent.GetError() {
		t.Errorf("error = %q, want %q", got.GetError(), sent.GetError())
	}
}
