// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: quorra/v1/quorra.proto

// The protocol between a worker and the server.
//
// The package carries a version. A change that a running worker cannot
// understand goes into quorra.v2 beside this, so that a server can answer
// both while the workers are replaced. Without the version there is no way to
// do that except by taking everything down at once.

package quorrapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Outcome is what the worker reports.
type Outcome int32

const (
	// The server refuses this value. A field left unset must not mean success,
	// because that is what an older or broken client sends.
	Outcome_OUTCOME_UNSPECIFIED Outcome = 0
	Outcome_OUTCOME_SUCCEEDED   Outcome = 1
	Outcome_OUTCOME_FAILED      Outcome = 2
	// The worker read the job and says no attempt will finish it. The server
	// buries the job at once, whatever its attempt count.
	//
	// A server built before this value sees a number it does not know, and the
	// mapping it already has answers with an error rather than reading an
	// unknown number as a success. That is why the unset value is not success.
	Outcome_OUTCOME_REFUSED Outcome = 3
)

// Enum value maps for Outcome.
var (
	Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_SUCCEEDED",
		2: "OUTCOME_FAILED",
		3: "OUTCOME_REFUSED",
	}
	Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"OUTCOME_SUCCEEDED":   1,
		"OUTCOME_FAILED":      2,
		"OUTCOME_REFUSED":     3,
	}
)

func (x Outcome) Enum() *Outcome {
	p := new(Outcome)
	*p = x
	return p
}

func (x Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_quorra_v1_quorra_proto_enumTypes[0].Descriptor()
}

func (Outcome) Type() protoreflect.EnumType {
	return &file_quorra_v1_quorra_proto_enumTypes[0]
}

func (x Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome.Descriptor instead.
func (Outcome) EnumDescriptor() ([]byte, []int) {
	return file_quorra_v1_quorra_proto_rawDescGZIP(), []int{0}
}

// Job is one piece of work.
type Job struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// payload is the JSON the client submitted, as bytes. The server does not
	// look inside it.
	Payload  []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Queue    string `protobuf:"bytes,4,opt,name=queue,proto3" json:"queue,omitempty"`
	Priority int32  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	// attempts counts this run as well as the ones before it, so the first run
	// of a job reports 1.
	Attempts   int32 `protobuf:"varint,6,opt,name=attempts,proto3" json:"attempts,omitempty"`
	MaxRetries int32 `protobuf:"varint,7,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	// lease_id must be sent back in the report. A job whose lease has been
	// taken back carries a different one, and the report is then refused.
	LeaseId string `protobuf:"bytes,8,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	// lease_expires_at is when the server takes the job back. A worker still
	// running at that moment is going to have its work repeated by somebody
	// else, so it is worth checking.
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	RunAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=run_at,json=runAt,proto3" json:"run_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_quorra_v1_quorra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_quorra_v1_quorra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_quorra_v1_quorra_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Job) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Job) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *Job) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Job) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Job) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Job) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *Job) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

func (x *Job) GetRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RunAt
	}
	return nil
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type LeaseRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WorkerId string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Queue    string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	MaxJobs  int32                  `protobuf:"varint,3,opt,name=max_jobs,json=maxJobs,proto3" json:"max_jobs,omitempty"`
	// lease_ttl is how long the worker asks to hold the jobs. A Duration and
	// not a count of seconds, so that a wrong unit cannot be sent silently.
	LeaseTtl      *durationpb.Duration `protobuf:"bytes,4,opt,name=lease_ttl,json=leaseTtl,proto3" json:"lease_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRequest) Reset() {
	*x = LeaseRequest{}
	mi := &file_quorra_v1_quorra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRequest) ProtoMessage() {}

func (x *LeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quorra_v1_quorra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRequest.ProtoReflect.Descriptor instead.
func (*LeaseRequest) Descriptor() ([]byte, []int) {
	return file_quorra_v1_quorra_proto_rawDescGZIP(), []int{1}
}

func (x *LeaseRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *LeaseRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *LeaseRequest) GetMaxJobs() int32 {
	if x != nil {
		return x.MaxJobs
	}
	return 0
}

func (x *LeaseRequest) GetLeaseTtl() *durationpb.Duration {
	if x != nil {
		return x.LeaseTtl
	}
	return nil
}

type LeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseResponse) Reset() {
	*x = LeaseResponse{}
	mi := &file_quorra_v1_quorra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseResponse) ProtoMessage() {}

func (x *LeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quorra_v1_quorra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseResponse.ProtoReflect.Descriptor instead.
func (*LeaseResponse) Descriptor() ([]byte, []int) {
	return file_quorra_v1_quorra_proto_rawDescGZIP(), []int{2}
}

func (x *LeaseResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type ReportRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	JobId    string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	LeaseId  string                 `protobuf:"bytes,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Outcome  Outcome                `protobuf:"varint,4,opt,name=outcome,proto3,enum=quorra.v1.Outcome" json:"outcome,omitempty"`
	// error is kept on the job and shown in the dashboard. It is ignored when
	// the outcome is a success.
	Error string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// result is what the job produced, as JSON. It is kept only when the
	// outcome is a success, because the output of an attempt that failed is not
	// an output.
	//
	// The server bounds it. A queue is not a place to put a large value: put
	// that where it belongs and report a reference to it here.
	Result        []byte `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_quorra_v1_quorra_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quorra_v1_quorra_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_quorra_v1_quorra_proto_rawDescGZIP(), []int{3}
}

func (x *ReportRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReportRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReportRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ReportRequest) GetOutcome() Outcome {
	if x != nil {
		return x.Outcome
	}
	return Outcome_OUTCOME_UNSPECIFIED
}

func (x *ReportRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReportRequest) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type HeartbeatRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	JobId    string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	LeaseId  string                 `protobuf:"bytes,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	// extend_by is how much longer the worker is asking for, measured from the
	// moment the server handles the call.
	ExtendBy      *durationpb.Duration `protobuf:"bytes,4,opt,name=extend_by,json=extendBy,proto3" json:"extend_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_quorra_v1_quorra_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quorra_v1_quorra_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_quorra_v1_quorra_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *HeartbeatRequest) GetExtendBy() *durationpb.Duration {
	if x != nil {
		return x.ExtendBy
	}
	return nil
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// lease_expires_at is the new expiry. A worker that is close to it and
	// still working knows its next heartbeat matters.
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_quorra_v1_quorra_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quorra_v1_quorra_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_quorra_v1_quorra_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

type ReportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is where the job ended up: pending when it will be retried,
	// succeeded, or dead.
	Status   string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Attempts int32  `protobuf:"varint,2,opt,name=attempts,proto3" json:"attempts,omitempty"`
	// run_at is when a retried job comes back. It holds the backoff the server
	// applied, so a worker can log it.
	RunAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=run_at,json=runAt,proto3" json:"run_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_quorra_v1_quorra_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quorra_v1_quorra_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_quorra_v1_quorra_proto_rawDescGZIP(), []int{6}
}

func (x *ReportResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportResponse) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *ReportResponse) GetRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RunAt
	}
	return nil
}

// WatchRequest asks to be told when a queue may have work.
type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// worker_id names the worker, for the server log. It grants nothing: the
	// key in the call metadata is what says a caller may watch.
	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// queues are the queues to be told about. Empty is refused rather than
	// read as "all of them": a worker that watched every queue would be woken
	// by work it cannot take.
	Queues        []string `protobuf:"bytes,2,rep,name=queues,proto3" json:"queues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_quorra_v1_quorra_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quorra_v1_quorra_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_quorra_v1_quorra_proto_rawDescGZIP(), []int{7}
}

func (x *WatchRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WatchRequest) GetQueues() []string {
	if x != nil {
		return x.Queues
	}
	return nil
}

// WatchResponse says that a queue may have work.
//
// It carries no job. Handing a job down this stream would make it a second
// way to lease one, with its own rules about leases and its own way to go
// wrong, and Lease is the call that already does it.
type WatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// queue is the queue that may have work.
	Queue string `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	// reason says what made the server send this, for a log line. It is not
	// something to branch on: a worker that treated one reason differently
	// from another would depend on a detail of when the server notices things.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_quorra_v1_quorra_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quorra_v1_quorra_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_quorra_v1_quorra_proto_rawDescGZIP(), []int{8}
}

func (x *WatchResponse) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *WatchResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_quorra_v1_quorra_proto protoreflect.FileDescriptor

const file_quorra_v1_quorra_proto_rawDesc = "" +
	"\n" +
	"\x16quorra/v1/quorra.proto\x12\tquorra.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x03\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x14\n" +
	"\x05queue\x18\x04 \x01(\tR\x05queue\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x1a\n" +
	"\battempts\x18\x06 \x01(\x05R\battempts\x12\x1f\n" +
	"\vmax_retries\x18\a \x01(\x05R\n" +
	"maxRetries\x12\x19\n" +
	"\blease_id\x18\b \x01(\tR\aleaseId\x12D\n" +
	"\x10lease_expires_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\x121\n" +
	"\x06run_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x05runAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x94\x01\n" +
	"\fLeaseRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x19\n" +
	"\bmax_jobs\x18\x03 \x01(\x05R\amaxJobs\x126\n" +
	"\tlease_ttl\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bleaseTtl\"3\n" +
	"\rLeaseResponse\x12\"\n" +
	"\x04jobs\x18\x01 \x03(\v2\x0e.quorra.v1.JobR\x04jobs\"\xba\x01\n" +
	"\rReportRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\tR\aleaseId\x12,\n" +
	"\aoutcome\x18\x04 \x01(\x0e2\x12.quorra.v1.OutcomeR\aoutcome\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x16\n" +
	"\x06result\x18\x06 \x01(\fR\x06result\"\x99\x01\n" +
	"\x10HeartbeatRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\tR\aleaseId\x126\n" +
	"\textend_by\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bextendBy\"Y\n" +
	"\x11HeartbeatResponse\x12D\n" +
	"\x10lease_expires_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\"w\n" +
	"\x0eReportResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\battempts\x18\x02 \x01(\x05R\battempts\x121\n" +
	"\x06run_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05runAt\"C\n" +
	"\fWatchRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06queues\x18\x02 \x03(\tR\x06queues\"=\n" +
	"\rWatchResponse\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*b\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11OUTCOME_SUCCEEDED\x10\x01\x12\x12\n" +
	"\x0eOUTCOME_FAILED\x10\x02\x12\x13\n" +
	"\x0fOUTCOME_REFUSED\x10\x032\x8f\x02\n" +
	"\fQueueService\x12:\n" +
	"\x05Lease\x12\x17.quorra.v1.LeaseRequest\x1a\x18.quorra.v1.LeaseResponse\x12=\n" +
	"\x06Report\x12\x18.quorra.v1.ReportRequest\x1a\x19.quorra.v1.ReportResponse\x12F\n" +
	"\tHeartbeat\x12\x1b.quorra.v1.HeartbeatRequest\x1a\x1c.quorra.v1.HeartbeatResponse\x12<\n" +
	"\x05Watch\x12\x17.quorra.v1.WatchRequest\x1a\x18.quorra.v1.WatchResponse0\x01B>Z<github.com/Stiven-Gjekaj/GoQuorra/internal/quorrapb;quorrapbb\x06proto3"

var (
	file_quorra_v1_quorra_proto_rawDescOnce sync.Once
	file_quorra_v1_quorra_proto_rawDescData []byte
)

func file_quorra_v1_quorra_proto_rawDescGZIP() []byte {
	file_quorra_v1_quorra_proto_rawDescOnce.Do(func() {
		file_quorra_v1_quorra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quorra_v1_quorra_proto_rawDesc), len(file_quorra_v1_quorra_proto_rawDesc)))
	})
	return file_quorra_v1_quorra_proto_rawDescData
}

var file_quorra_v1_quorra_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_quorra_v1_quorra_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_quorra_v1_quorra_proto_goTypes = []any{
	(Outcome)(0),                  // 0: quorra.v1.Outcome
	(*Job)(nil),                   // 1: quorra.v1.Job
	(*LeaseRequest)(nil),          // 2: quorra.v1.LeaseRequest
	(*LeaseResponse)(nil),         // 3: quorra.v1.LeaseResponse
	(*ReportRequest)(nil),         // 4: quorra.v1.ReportRequest
	(*HeartbeatRequest)(nil),      // 5: quorra.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 6: quorra.v1.HeartbeatResponse
	(*ReportResponse)(nil),        // 7: quorra.v1.ReportResponse
	(*WatchRequest)(nil),          // 8: quorra.v1.WatchRequest
	(*WatchResponse)(nil),         // 9: quorra.v1.WatchResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 11: google.protobuf.Duration
}
var file_quorra_v1_quorra_proto_depIdxs = []int32{
	10, // 0: quorra.v1.Job.lease_expires_at:type_name -> google.protobuf.Timestamp
	10, // 1: quorra.v1.Job.run_at:type_name -> google.protobuf.Timestamp
	10, // 2: quorra.v1.Job.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: quorra.v1.LeaseRequest.lease_ttl:type_name -> google.protobuf.Duration
	1,  // 4: quorra.v1.LeaseResponse.jobs:type_name -> quorra.v1.Job
	0,  // 5: quorra.v1.ReportRequest.outcome:type_name -> quorra.v1.Outcome
	11, // 6: quorra.v1.HeartbeatRequest.extend_by:type_name -> google.protobuf.Duration
	10, // 7: quorra.v1.HeartbeatResponse.lease_expires_at:type_name -> google.protobuf.Timestamp
	10, // 8: quorra.v1.ReportResponse.run_at:type_name -> google.protobuf.Timestamp
	2,  // 9: quorra.v1.QueueService.Lease:input_type -> quorra.v1.LeaseRequest
	4,  // 10: quorra.v1.QueueService.Report:input_type -> quorra.v1.ReportRequest
	5,  // 11: quorra.v1.QueueService.Heartbeat:input_type -> quorra.v1.HeartbeatRequest
	8,  // 12: quorra.v1.QueueService.Watch:input_type -> quorra.v1.WatchRequest
	3,  // 13: quorra.v1.QueueService.Lease:output_type -> quorra.v1.LeaseResponse
	7,  // 14: quorra.v1.QueueService.Report:output_type -> quorra.v1.ReportResponse
	6,  // 15: quorra.v1.QueueService.Heartbeat:output_type -> quorra.v1.HeartbeatResponse
	9,  // 16: quorra.v1.QueueService.Watch:output_type -> quorra.v1.WatchResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_quorra_v1_quorra_proto_init() }
func file_quorra_v1_quorra_proto_init() {
	if File_quorra_v1_quorra_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quorra_v1_quorra_proto_rawDesc), len(file_quorra_v1_quorra_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quorra_v1_quorra_proto_goTypes,
		DependencyIndexes: file_quorra_v1_quorra_proto_depIdxs,
		EnumInfos:         file_quorra_v1_quorra_proto_enumTypes,
		MessageInfos:      file_quorra_v1_quorra_proto_msgTypes,
	}.Build()
	File_quorra_v1_quorra_proto = out.File
	file_quorra_v1_quorra_proto_goTypes = nil
	file_quorra_v1_quorra_proto_depIdxs = nil
}
