// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: quorra/v1/quorra.proto

// The protocol between a worker and the server.
//
// The package carries a version. A change that a running worker cannot
// understand goes into quorra.v2 beside this, so that a server can answer
// both while the workers are replaced. Without the version there is no way to
// do that except by taking everything down at once.

package quorrapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QueueService_Lease_FullMethodName     = "/quorra.v1.QueueService/Lease"
	QueueService_Report_FullMethodName    = "/quorra.v1.QueueService/Report"
	QueueService_Heartbeat_FullMethodName = "/quorra.v1.QueueService/Heartbeat"
)

// QueueServiceClient is the client API for QueueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// QueueService is what a worker talks to.
type QueueServiceClient interface {
	// Lease asks for work and returns what is available now.
	//
	// This is one call and one answer, where the previous version declared a
	// server stream. That stream sent whatever was ready and then closed, which
	// is a single answer written in a way that costs the client a receive loop
	// and an end of file to handle. Nothing was ever pushed down it.
	//
	// A stream that stays open and pushes a job the moment it arrives is a real
	// design, and it is not this one. docs/milestones.md says what it would
	// need.
	Lease(ctx context.Context, in *LeaseRequest, opts ...grpc.CallOption) (*LeaseResponse, error)
	// Report says what happened to a job.
	//
	// One call, with the outcome as a field that the server reads. The previous
	// version had AckJob and NackJob, and a success field on the message that
	// no code ever read, so a worker that set it to false and called AckJob was
	// recorded as having succeeded.
	Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	// Heartbeat pushes the expiry of a lease further out.
	//
	// A worker calls it while a handler is still running, so that a job slower
	// than the lease it was given is not taken back and handed to somebody
	// else. The refusal is the useful part: a job that was cancelled, or one
	// whose lease already ran out and was reclaimed, fails this call with
	// FAILED_PRECONDITION, and that is how a worker learns to stop.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type queueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueueServiceClient(cc grpc.ClientConnInterface) QueueServiceClient {
	return &queueServiceClient{cc}
}

func (c *queueServiceClient) Lease(ctx context.Context, in *LeaseRequest, opts ...grpc.CallOption) (*LeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaseResponse)
	err := c.cc.Invoke(ctx, QueueService_Lease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, QueueService_Report_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, QueueService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueueServiceServer is the server API for QueueService service.
// All implementations must embed UnimplementedQueueServiceServer
// for forward compatibility.
//
// QueueService is what a worker talks to.
type QueueServiceServer interface {
	// Lease asks for work and returns what is available now.
	//
	// This is one call and one answer, where the previous version declared a
	// server stream. That stream sent whatever was ready and then closed, which
	// is a single answer written in a way that costs the client a receive loop
	// and an end of file to handle. Nothing was ever pushed down it.
	//
	// A stream that stays open and pushes a job the moment it arrives is a real
	// design, and it is not this one. docs/milestones.md says what it would
	// need.
	Lease(context.Context, *LeaseRequest) (*LeaseResponse, error)
	// Report says what happened to a job.
	//
	// One call, with the outcome as a field that the server reads. The previous
	// version had AckJob and NackJob, and a success field on the message that
	// no code ever read, so a worker that set it to false and called AckJob was
	// recorded as having succeeded.
	Report(context.Context, *ReportRequest) (*ReportResponse, error)
	// Heartbeat pushes the expiry of a lease further out.
	//
	// A worker calls it while a handler is still running, so that a job slower
	// than the lease it was given is not taken back and handed to somebody
	// else. The refusal is the useful part: a job that was cancelled, or one
	// whose lease already ran out and was reclaimed, fails this call with
	// FAILED_PRECONDITION, and that is how a worker learns to stop.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedQueueServiceServer()
}

// UnimplementedQueueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueueServiceServer struct{}

func (UnimplementedQueueServiceServer) Lease(context.Context, *LeaseRequest) (*LeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lease not implemented")
}
func (UnimplementedQueueServiceServer) Report(context.Context, *ReportRequest) (*ReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedQueueServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedQueueServiceServer) mustEmbedUnimplementedQueueServiceServer() {}
func (UnimplementedQueueServiceServer) testEmbeddedByValue()                      {}

// UnsafeQueueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueueServiceServer will
// result in compilation errors.
type UnsafeQueueServiceServer interface {
	mustEmbedUnimplementedQueueServiceServer()
}

func RegisterQueueServiceServer(s grpc.ServiceRegistrar, srv QueueServiceServer) {
	// If the following call pancis, it indicates UnimplementedQueueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueueService_ServiceDesc, srv)
}

func _QueueService_Lease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).Lease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_Lease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).Lease(ctx, req.(*LeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_Report_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).Report(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueueService_ServiceDesc is the grpc.ServiceDesc for QueueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quorra.v1.QueueService",
	HandlerType: (*QueueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lease",
			Handler:    _QueueService_Lease_Handler,
		},
		{
			MethodName: "Report",
			Handler:    _QueueService_Report_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _QueueService_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quorra/v1/quorra.proto",
}
